# General purpose loader for require_relatived libraries
require 'rubygems'
require 'open3'
require 'yaml'
require 'logger'
require 'fileutils'
require_relative 'colorize'
require_relative 'gitbase'
require_relative 'blissrunner'
require_relative 'dockerrunner'
require_relative 'cloud/dockercmd'
require_relative 'cloud/localrunner'
